/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.upperproject.upper;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.net.URL;


/**
 *
 * @author USER
 */
public class Telalogin extends javax.swing.JFrame {

    /**
     * Creates new form Telalogin
     */
    public Telalogin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        botaoEntrar = new javax.swing.JButton();
        Trello = new javax.swing.JButton();
        Github = new javax.swing.JButton();
        CaixaSenha = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UpperTech");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setBackground(new java.awt.Color(0, 255, 133));
        txtLogin.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(0, 153, 0));
        txtLogin.setBorder(null);
        txtLogin.setCaretColor(new java.awt.Color(0, 153, 0));
        txtLogin.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 194, 180, 34));

        txtSenha.setBackground(new java.awt.Color(0, 255, 133));
        txtSenha.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(0, 153, 0));
        txtSenha.setBorder(null);
        txtSenha.setCaretColor(new java.awt.Color(0, 153, 0));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 273, 190, 34));

        botaoEntrar.setContentAreaFilled(false);
        botaoEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 325, 230, 34));

        Trello.setContentAreaFilled(false);
        Trello.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Trello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrelloActionPerformed(evt);
            }
        });
        getContentPane().add(Trello, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 24, 24));

        Github.setContentAreaFilled(false);
        Github.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Github.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GithubActionPerformed(evt);
            }
        });
        getContentPane().add(Github, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 210, 24, 24));

        CaixaSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CaixaSenha.setForeground(new java.awt.Color(0, 153, 0));
        CaixaSenha.setText("Mostrar Senha");
        CaixaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 365, 110, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/TelaLogin.png"))); // NOI18N
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 650, 430));

        jMenu3.setText("File");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TrelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrelloActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://trello.com/b/TTYmIaED/projeto-uppertech?utm_source=eval-email&utm_medium=email&utm_campaign=board-invite").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_TrelloActionPerformed

    private void GithubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GithubActionPerformed
     try{
            Desktop.getDesktop().browse(new URL("https://github.com/UpperTechh").toURI());
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_GithubActionPerformed
    
    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
    if(txtLogin.getText().equals("Upper@gmail.com")&&txtSenha.getText().equals("321")){
    Op TelaOp = new Op();
    TelaOp.setVisible(true);
    this.setVisible(false);
    }else{
        JOptionPane.showMessageDialog(null, "DADOS INVALIDOS!");
    }
    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtLoginActionPerformed
   
    private void CaixaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaSenhaActionPerformed
        // TODO add your handling code here:
       if(CaixaSenha.isSelected()){
           txtSenha.setEchoChar((char)0);
       }else{
           txtSenha.setEchoChar('*');
       
       }
        
    }//GEN-LAST:event_CaixaSenhaActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telalogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CaixaSenha;
    private javax.swing.JButton Github;
    private javax.swing.JButton Trello;
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        
    }
}
